services:
  - type: web
    name: senninproxy
    env: node
    plan: free 
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 
      - key: PORT
        value: 10000
